# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quantized.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2
from tensorflow.core.framework import graph_pb2 as tensorflow_dot_core_dot_framework_dot_graph__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='quantized.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fquantized.proto\x1a%tensorflow/core/framework/types.proto\x1a%tensorflow/core/framework/graph.proto\"\xe3\x01\n\rQuantizedItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x05\x64type\x18\x02 \x01(\x0e\x32\x14.tensorflow.DataType\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\x19\n\x05vtype\x18\x04 \x01(\x0e\x32\n.ValueType\x12\x0c\n\x04\x62\x61se\x18\x05 \x01(\x02\x12\x0c\n\x04step\x18\x06 \x01(\x02\x12\r\n\x05index\x18\x07 \x03(\r\x12\x11\n\tint_table\x18\x08 \x03(\x11\x12\x13\n\x0b\x66loat_table\x18\t \x03(\x02\x12\x0f\n\x07int_raw\x18\n \x03(\x11\x12\x11\n\tfloat_raw\x18\x0b \x03(\x02\"T\n\x0eQuantizedGraph\x12#\n\x05graph\x18\x01 \x01(\x0b\x32\x14.tensorflow.GraphDef\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.QuantizedItem*+\n\tValueType\x12\x07\n\x03RAW\x10\x00\x12\n\n\x06SIMPLE\x10\x01\x12\t\n\x05TABLE\x10\x02\x42\x03\xf8\x01\x00\x62\x06proto3')
  ,
  dependencies=[tensorflow_dot_core_dot_framework_dot_types__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_graph__pb2.DESCRIPTOR,])

_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RAW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMPLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TABLE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=413,
  serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_VALUETYPE)

ValueType = enum_type_wrapper.EnumTypeWrapper(_VALUETYPE)
RAW = 0
SIMPLE = 1
TABLE = 2



_QUANTIZEDITEM = _descriptor.Descriptor(
  name='QuantizedItem',
  full_name='QuantizedItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='QuantizedItem.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='QuantizedItem.dtype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='QuantizedItem.shape', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vtype', full_name='QuantizedItem.vtype', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='base', full_name='QuantizedItem.base', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step', full_name='QuantizedItem.step', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='QuantizedItem.index', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_table', full_name='QuantizedItem.int_table', index=7,
      number=8, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_table', full_name='QuantizedItem.float_table', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_raw', full_name='QuantizedItem.int_raw', index=9,
      number=10, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_raw', full_name='QuantizedItem.float_raw', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=325,
)


_QUANTIZEDGRAPH = _descriptor.Descriptor(
  name='QuantizedGraph',
  full_name='QuantizedGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph', full_name='QuantizedGraph.graph', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='QuantizedGraph.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=411,
)

_QUANTIZEDITEM.fields_by_name['dtype'].enum_type = tensorflow_dot_core_dot_framework_dot_types__pb2._DATATYPE
_QUANTIZEDITEM.fields_by_name['vtype'].enum_type = _VALUETYPE
_QUANTIZEDGRAPH.fields_by_name['graph'].message_type = tensorflow_dot_core_dot_framework_dot_graph__pb2._GRAPHDEF
_QUANTIZEDGRAPH.fields_by_name['items'].message_type = _QUANTIZEDITEM
DESCRIPTOR.message_types_by_name['QuantizedItem'] = _QUANTIZEDITEM
DESCRIPTOR.message_types_by_name['QuantizedGraph'] = _QUANTIZEDGRAPH
DESCRIPTOR.enum_types_by_name['ValueType'] = _VALUETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuantizedItem = _reflection.GeneratedProtocolMessageType('QuantizedItem', (_message.Message,), dict(
  DESCRIPTOR = _QUANTIZEDITEM,
  __module__ = 'quantized_pb2'
  # @@protoc_insertion_point(class_scope:QuantizedItem)
  ))
_sym_db.RegisterMessage(QuantizedItem)

QuantizedGraph = _reflection.GeneratedProtocolMessageType('QuantizedGraph', (_message.Message,), dict(
  DESCRIPTOR = _QUANTIZEDGRAPH,
  __module__ = 'quantized_pb2'
  # @@protoc_insertion_point(class_scope:QuantizedGraph)
  ))
_sym_db.RegisterMessage(QuantizedGraph)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\000'))
# @@protoc_insertion_point(module_scope)
