/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xinmei.swig;

public class RnnModuleJNI {
  public final static native long new_RnnDict(byte[] jarg1, String jarg3, String jarg4, int[] jarg5, long jarg6, long jarg7, boolean jarg8);
  public final static native void delete_RnnDict(long jarg1);
  public final static native void RnnDict_addState(long jarg1, RnnDict jarg1_, String jarg2, String jarg3, int[] jarg4, long jarg5, boolean jarg6);
  public final static native void RnnDict_predict(long jarg1, RnnDict jarg1_, int[] jarg2, long jarg3, boolean jarg4, int jarg5);
  public final static native int RnnDict_getWordId(long jarg1, RnnDict jarg1_, int jarg2);
  public final static native float RnnDict_getP(long jarg1, RnnDict jarg1_, int jarg2);
  public final static native long RnnDict_lastPredictStepCount(long jarg1, RnnDict jarg1_);
  public final static native int RnnDict_lastPredictTimeInMillis(long jarg1, RnnDict jarg1_);
}
